spring:
  application:
    name: otryx-example-provider

otryx:
  rpc:
    registry:
      type: nacos
      endpoints: 127.0.0.1:8848
      namespace: public
      nacos:
        group: OTRYX_RPC
        cluster: DEFAULT
    server:
      host: 0.0.0.0
      port: 19090
      advertised-host: 127.0.0.1
      advertised-port: 19090
      drain-timeout: 5s
      control-plane-timeout: 3s
