<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.peachsoft.otryx</groupId><artifactId>otryx-rpc</artifactId><version>${revision}</version><relativePath>../pom.xml</relativePath>
    </parent>
    <artifactId>otryx-registry</artifactId>
    <packaging>pom</packaging>
    <modules>
        <module>otryx-registry-etcd</module>
        <module>otryx-registry-nacos</module>
    </modules>
</project>
