#!/usr/bin/env python3
"""Synchronize Windows Cursor/Codex MCP adapters from one audited spec.

The generated default does not expose a MySQL server to Cursor and explicitly
disables it in Codex. Read-only DB access must be enforced by actual SQL GRANTs,
not by this generator, configuration comments, or an agent's instructions.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "config/agent-mcp.json"
CURSOR = ROOT / ".cursor/mcp.json"
CODEX = ROOT / ".codex/config.toml"
IDENTIFIER = re.compile(r"^[a-z][a-z0-9-]*$")
ENVIRONMENT = re.compile(r"^[A-Z][A-Z0-9_]*$")


def load_spec(path: Path = SOURCE) -> list[dict]:
    data = json.loads(path.read_text(encoding="utf-8"))
    if data.get("schema_version") != 1 or data.get("platform") != "windows-cmd-npx":
        raise ValueError("Unsupported MCP registry schema or platform")
    servers = data.get("servers")
    if not isinstance(servers, list) or not servers:
        raise ValueError("MCP registry must contain servers")
    names = set()
    for server in servers:
        name = server.get("id")
        if not isinstance(name, str) or not IDENTIFIER.fullmatch(name):
            raise ValueError(f"Invalid MCP server ID: {name!r}")
        if name in names:
            raise ValueError(f"Duplicate MCP server ID: {name}")
        names.add(name)
        package = server.get("package")
        if not isinstance(package, str) or not re.fullmatch(
            r"[@a-zA-Z0-9._/-]+", package
        ):
            raise ValueError(f"Invalid package reference for {name}")
        args = server.get("args", [])
        if not isinstance(args, list) or not all(
            isinstance(arg, str) for arg in args
        ):
            raise ValueError(f"Invalid args for {name}")
        variables = server.get("env_vars", [])
        if not isinstance(variables, list) or not all(
            isinstance(var, str) and ENVIRONMENT.fullmatch(var)
            for var in variables
        ):
            raise ValueError(f"Invalid environment names for {name}")
        static = server.get("static_env", {})
        if not isinstance(static, dict) or not all(
            isinstance(k, str) and ENVIRONMENT.fullmatch(k)
            and isinstance(v, str) for k, v in static.items()
        ):
            raise ValueError(f"Invalid static environment for {name}")
        if set(static).intersection(variables):
            raise ValueError(f"Conflicting dynamic/static environment for {name}")
        if not isinstance(server.get("enabled_by_default"), bool):
            raise ValueError(f"enabled_by_default must be boolean for {name}")
        if "password" in json.dumps(static).lower() or "token" in json.dumps(static).lower():
            raise ValueError(f"Do not embed secrets in static environment: {name}")
    mysql = next((s for s in servers if s["id"] == "mysql"), None)
    if mysql is None or mysql["enabled_by_default"]:
        raise ValueError("MySQL must be present and disabled by default")
    return servers


def command(server: dict, platform: str) -> list[str]:
    return [
        "/c", "npx", "-y", server["package"],
        *(platform if arg == "{workspace}" else arg
          for arg in server.get("args", [])),
    ]


def render_cursor(servers: list[dict]) -> str:
    active = {}
    for server in servers:
        if not server["enabled_by_default"]:
            continue
        variables = {
            name: "${env:" + name + "}"
            for name in server.get("env_vars", [])
        }
        active[server["id"]] = {
            "type": "stdio",
            "command": "cmd",
            "args": command(server, "${workspaceFolder}"),
            **({"env": {**server.get("static_env", {}), **variables}}
               if variables or server.get("static_env") else {}),
        }
    return json.dumps({"mcpServers": active}, indent=2, ensure_ascii=False) + "\n"


def render_codex(servers: list[dict]) -> str:
    lines = [
        "# Generated by scripts/sync_agent_mcp.py from config/agent-mcp.json.",
        "# Do not edit directly. Secrets come from the client environment.",
        "# MySQL is disabled until separately authorized and DB-grant verified.",
        "",
    ]
    for server in servers:
        sid = server["id"]
        lines.extend([
            f'[mcp_servers."{sid}"]',
            'command = "cmd"',
            "args = " + json.dumps(command(server, ".")),
            f'enabled = {str(server["enabled_by_default"]).lower()}',
            "required = false",
            "startup_timeout_sec = 60",
            "tool_timeout_sec = 60",
        ])
        if server.get("env_vars"):
            lines.append("env_vars = " + json.dumps(server["env_vars"]))
        lines.append("")
        if server.get("static_env"):
            lines.append(f'[mcp_servers."{sid}".env]')
            for key, value in server["static_env"].items():
                lines.append(
                    json.dumps(key) + " = " + json.dumps(value))
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def synchronize(check: bool = False, root: Path = ROOT) -> list[str]:
    servers = load_spec(root / "config/agent-mcp.json")
    targets = [
        (root / ".cursor/mcp.json", render_cursor(servers)),
        (root / ".codex/config.toml", render_codex(servers)),
    ]
    drift = []
    for path, expected in targets:
        actual = path.read_text(encoding="utf-8") if path.is_file() else None
        if actual == expected:
            continue
        if check:
            drift.append(str(path.relative_to(root)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(expected, encoding="utf-8", newline="\n")
    return drift


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    try:
        drift = synchronize(check=args.check)
    except (OSError, ValueError, json.JSONDecodeError) as error:
        print(f"Invalid agent MCP configuration: {error}", file=sys.stderr)
        return 1
    if drift:
        print("Generated MCP adapter drift: " + ", ".join(drift),
              file=sys.stderr)
        return 1
    print("Agent MCP configuration is valid and synchronized.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
