spring:
  application:
    name: peach-rpc-example-consumer

peach:
  rpc:
    registry:
      type: nacos
      endpoints: 127.0.0.1:8848
      namespace: public
      nacos:
        group: PEACH_RPC
        cluster: DEFAULT
    client:
      timeout: 3s
      resilience:
        max-attempts: 2
