spring:
  application:
    name: otryx-example-consumer

otryx:
  rpc:
    registry:
      type: nacos
      endpoints: 127.0.0.1:8848
      namespace: public
      nacos:
        group: OTRYX_RPC
        cluster: DEFAULT
    client:
      timeout: 3s
      resilience:
        max-attempts: 2
